services:
  anoto-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anoto-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - anoto-network

networks:
  anoto-network:
    external: true
